### ISSUE TITLE
Immutable response objects

### ISSUE THREAD

**Issue by rickle-msft** [Azure/autorest.java#110]
Classes that are returned from REST APIs should be immutable after deserialization; that is, we there shouldn't be any with*() apis. There is no value in being able to set those fields and it confuse the customer if they think that setting those fields will have any effect on their actual stored data.

**Comment by RikkiGibson** [comment]
Consider `Services.setProperties(StorageServiceProperties)`. This seems like an object that users would create on their side and the runtime would serialize before sending to the server in order to actually set the service properties. `getProperties` returns an object of the same type. Loads of services wind up representing their APIs this way.

We can't elide the withers for this case, and users still have to learn that classes under the `models` package are "plain old data" and setting their properties doesn't cause server side changes to occur-- I expect users to pick up on this because the return type and doc of these methods don't indicate 1. any network operation taking place and 2. any chance of failure.

**Comment by RikkiGibson** [comment]
Please reopen if you feel there is a reasonable solution to this from our side. It seems to me like the overhead of detecting when a certain model is used only in a return type and not in a parameter type and therefore removing the `with*()` methods is maybe not worth it, especially if customers are consuming these types in their code and would like to synthetically create instances for their own testing.
