### ISSUE TITLE
LLC, partial update for module-info.java

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1308]
Merge generated module-info.java with existing module-info.java, when `partial-update` option is enabled,

Reason:

Generated module-info.java will be e.g.
```java
module com.azure.messaging.webpubsubnew {
    requires transitive com.azure.core;

    exports com.azure.messaging.webpubsubnew;
}
```

Then dev can customize it to be e.g.
```java
module com.azure.messaging.webpubsubnew {
    requires transitive com.azure.core;

    exports com.azure.messaging.webpubsubnew;
    exports com.azure.messaging.webpubsubnew.models;
}
```
commit to demonstrate https://github.com/Azure/azure-sdk-for-java/pull/26473/commits/094bcbc1092688d551309a32a68c59db48d6c11b

These customization needs to be perserved.

**Comment by haolingdong-msft** [comment]
module-info.java is a bit different from class/interface files because it does not have `@Generated` annotation to distinguish which part is manual and which part is generated.
There are below ways to support partial update in module-info.java:
1. If user has customized module-info.java, then we always use the customized file. We can compare if the user's existing module-info.java is different from newly generated module-info.java, if it's different, then we use the existing module-info.java. This is the most simple way, but this can not reflect on any changes to module-info.java when codegen changes.
2. We keep the existing module-info.java, then compare each statement in generated module-info.java with existing statements, if the statement in generated file is not found in existing file, then we will add the generated statement into existing module-info.java. 
3. We keep the generated module-info.java, then compare each statement in existing module-info.java with generated statements, if the statement in existing file is not found in generated file, then we will add the existing statement into generated module-info.java.

My personal preference is option 2, as it will keep the format of existing module-info.java and can reflect on the changes to module-info.java in codegen. Please let me know if you have any preference.

**Comment by weidongxu-microsoft** [comment]
2 (or 3) would be optimal, while 1 is actually good enough in near term (at present we would not expect dev to reduce the scope of `exports` or `opens`).

If you take 2, make sure you can handle e.g. dev change from "generated"
```
    opens com.azure.storage.blob.models to
        com.fasterxml.jackson.databind;
```
to "customized"
```
    opens com.azure.storage.blob.models to
        com.fasterxml.jackson.databind,
        com.azure.core;
```

**Comment by haolingdong-msft** [comment]
If 1 is good enough in near term, I will probably go with 1 at this time, if we have more complex scenario in the future, we then add Option2 logic. Please let me know if this works for you or not.

**Comment by weidongxu-microsoft** [comment]
Ok for me.
