### ISSUE TITLE
LLC, improve Javadoc on query with array

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1312]
Javadoc especially on query with array is almost useless.

Question: how to specify the query parameters in this `deleteByGuidsWithResponse`?
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-analytics-purview-catalog/1.0.0-beta.2/index.html

Answer (hope it is correct):
https://github.com/Azure/azure-sdk-for-java/blob/0bc0e0fc315fa19c164d530826ffb2e367861bc1/sdk/purview/azure-analytics-purview-catalog/src/samples/java/com/azure/analytics/purview/catalog/generated/EntityDeleteByGuids.java

**Comment by XiaofeiCao** [comment]
There are two solutions when query with array is encountered:

### Solution 1

  #### Add a description above the "Query Parameters"
  1. Content:
 ```java
/** 
 * Query parameters should be added through requestOptions e.g. <pre>{@code requestOptions.add("foo", bar); }</pre>, 
 * parameter names can be found below in "Query Parameters" section. 
 * /
```
		
  2. Change query parameter name in "Query Parameters" from parameter name to serialized name (ignore x-ms-client-name), so that user can set parameters correctly.
  3. Add an additional column named "Note"
  * For array with collection format "multi", add following into this column: 
    * values should be added one by one by calling RequestOptions.add for each value.
  * For array with other collection format and delimiter ",", add following: 
    * values should be joined into a single string delimited by ",", e.g. requestOptions.add("guid", "guid1,guid2");

  #### Overall comment looks like this:
```java
/**
 * Query parameters should be added through {@link RequestOptions#add} e.g. <pre>{@code requestOptions.add("foo", bar); }</pre>, 
 * parameter names can be found below in "Query Parameters" section. 
 * <p><strong>Query Parameters</strong>
 *
 * <table border="1">
 *     <caption>Query Parameters</caption>
 *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th><th>Note</th></tr>
 *     <tr><td>guid</td><td>String</td><td>Yes</td><td>An array of GUIDs of entities to list.</td><td>values should be added one by one by calling @{link RequestOptions#add} for each value</td></tr>
 *     <tr><td>minExtInfo</td><td>String</td><td>No</td><td>Whether to return minimal information for referred entities.</td><td></td></tr>
 *     <tr><td>ignoreRelationships</td><td>String</td><td>No</td><td>Whether to ignore relationship attributes.</td><td></td></tr>
 *     <tr><td>excludeRelationshipTypes</td><td>String</td><td>No</td><td>An array of the relationship types need to be excluded from the response.</td><td></td></tr>
 * </table>
```
### Solution2:
  #### Add an additional section "Call Example", and add some code samples to it, with comment on each line:
```java
/**
        * <p><strong>Call Example</strong></p>
	* <pre>{@code
	* RequestOptions requestOptions = new RequestOptions();
	* // An array of GUIDs of entities to list, with values guid1 and guid2 (in case collection format is "multi")
	* requestOptions.add("guid", guid1);
	* requestOptions.add("guid", guid2);
	* // An array of GUIDs of entities to list, with values guid1 and guid2 ((in case collection format is "csv, ssv, etc", and delimiter is ",")
	* requestOptions.add("guid", String.format("%s,%s", guid1, guid2));
	* //Whether to return minimal information for referred entities, with value minExtInfo
	* requestOptions.add("minExtInfo", minExtInfo);
	
	* Response<BinaryData> response = entityClient.listByGuidsWithResponse(otherPathParameters, requestOptions);
        * }</pre>
        * /
```

Hopefully I listed enough possibilities above...

My personal preference is solution1 since it adds minimal comments and easier to implement, while solution2 is probably more clearly to the end user.

Which one do you think should I take? Thanks.

**Comment by weidongxu-microsoft** [comment]
For 2, reading material here: https://github.com/Azure/azure-sdk-for-java/wiki/JavaDoc-with-CodeSnippet

**Comment by XiaofeiCao** [comment]
Thanks! I think I'll take solution 1 this time. Main reasons are:
1. Current examples don't contain all the parameters, e.g. 
* swagger parameters: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/data-plane/Azure.Analytics.Purview.Catalog/preview/2021-05-01-preview/purviewcatalog.json#L100
* corresponding examples: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/data-plane/Azure.Analytics.Purview.Catalog/preview/2021-05-01-preview/examples/Entity_ListByGuids.json#L2
2. Parameter names in "Query Parameters" section should to be the serialized names instead of client ones, as they are directly added through `requestOptions.add`. Solution1 will fix this.
3. If we implement solution1, examples can be added afterwards if necessary without confliction.

So the javadoc should be like:
```java
/**
 * Query parameters should be added through {@link RequestOptions#add} e.g. <pre>{@code requestOptions.add("foo", bar); }</pre>, 
 * parameter names can be found in "Query Parameters" section below. 
 * <p><strong>Query Parameters</strong>
 *
 * <table border="1">
 *     <caption>Query Parameters</caption>
 *     <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
 *     <tr><td>guid</td><td>String</td><td>Yes</td><td>An array of GUIDs of entities to list. In the form of ","-separated string.</td></tr>
 *     <tr><td>excludeRelationshipTypes</td><td>String</td><td>No</td><td>An array of the relationship types need to be excluded from the response. Call `RequestOptions.addQueryParam` to add string to array.</td></tr>
 *     <tr><td>ignoreRelationships</td><td>String</td><td>No</td><td>Whether to ignore relationship attributes.</td></tr>
 * </table>
```

**Comment by weidongxu-microsoft** [comment]
sorry, for 2, see https://github.com/Azure/azure-sdk-tools/blob/main/packages/java-packages/codesnippet-maven-plugin/README.md

**Comment by weidongxu-microsoft** [comment]
currently codesnippet tool has limit of max char 120 per line.

**Comment by XiaofeiCao** [comment]
It's weird that the plugin throws exception in `update-codesnippets` phase <strong>after</strong> it generates the javadoc...
