### ISSUE TITLE
Experiment Metrics Advisor (developer driven evolution)

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#1339]
As an experiment to confirm that DPG can grow to a meaningful SDK, we want to experiment on Metrics Advisor:
- Generate DPG of Metrics Advisor
- Grow the SDK to feature equivalence to the current SDK. To confirm feature equivalence, the testsuite needs to be runnable in live.

You _may_ decide to merge this work (as a refactoring), or to keep this work as an experiment that we don't merge.

Expected work is to take the _latest Swagger_ and rebuild the corresponding release.

**Comment by weidongxu-microsoft** [comment]
1. Start with raw swagger without customization and directives. Assume the swagger is fully reviewed and approved.
2. Apply customization to converge to existing lib.
3. Some customization in current lib is not allowed as it is breaking change, we will document it but not do the customization. (e.g. break 1 client to 2 clients after GA is not allowed as it breaks)

Not all REST API is to be covered, target is demonstration and documentation of customization, as well as which is allowed and not allowed in Java.

**Comment by haolingdong-msft** [comment]
I checked the APIs of Metrics Advisor and selected some APIs that need to be covered, proposed in below table. My selection is based on below reason. Please take a look and feel free to add/remove the APIs from below table. 


1. Contains APIs in both MetricsAdvisorAdministrationAsyncClient and MetricsAdvisorAsyncClient
2. Contains all the four methods appeared in swagger:  GET, POST, DELETE, PATCH
3. Contains create, delete, update and get operations.
4. Contains both paging and non-paging operation. (I checked there is no long running operation in MetricsAdvisor）

| API                                     | Client                                  | Path                                                                          | Method | Return value |
|-----------------------------------------|-----------------------------------------|-------------------------------------------------------------------------------|--------|--------------|
| getAlertsByAnomalyAlertingConfiguration | MetricsAdvisorAsyncClient               | /enrichment/anomalyDetection/configurations/{configurationId}/anomalies/query | POST   | PagedFlux    |
| getAnomalyDetectionConfiguration        | MetricsAdvisorAsyncClient               | /enrichment/anomalyDetection/configurations/{configurationId}                 | GET    | Mono         |
| updateAnomalyDetectionConfiguration     | MetricsAdvisorAsyncClient               | /enrichment/anomalyDetection/configurations/{configurationId}                 | PATCH  | Mono         |
| deleteAnomalyDetectionConfiguration     | MetricsAdvisorAsyncClient               | /enrichment/anomalyDetection/configurations/{configurationId}                 | DELETE | Mono<Void>   |
| createDataSourceCredential              | MetricsAdvisorAdministrationAsyncClient | /credentials                                                                  | POST   | Mono         |
| getDataFeed                             | MetricsAdvisorAdministrationAsyncClient | /dataFeeds/{dataFeedId}                                                       | GET    | Mono         |

**Comment by haolingdong-msft** [comment]
A quick update on this issue about what are done and TODOs:

What are done:

1. Swagger README configuration
I removed unused directives now, only directives to support POST on next page remains. (also remain one model MetricsAdvisorErrorCode because next page operation refer to this schema to avoid codegen failure)

2. Testing the set of APIs in the table.
I reused the existing unit test to verify our grow-up code since we keep the public method signature. I tried for PLAYBACK and LIVE, both tests passed.

3. Customized Authentication
Authentication part is also verified in LIVE test.

4. Model Conversion for PagedFlux and Mono
I used the PagedConverter Util rather than the deprecated .mapPage(), because deprecated method has some wrong behavior when iterating PagedIterable and breaks before iteration finished, it can't break in the middle of iteration.
[PagedFlux](https://github.com/haolingdong-msft/metrics-advisor-poc/blob/fdbfdb6f85b59042a559e8871b7c3c935fbaa365/src/main/java/com/azure/ai/metricsadvisor/administration/MetricsAdvisorAdministrationAsyncClient.java#L336-L336)
[Mono](https://github.com/haolingdong-msft/metrics-advisor-poc/blob/fdbfdb6f85b59042a559e8871b7c3c935fbaa365/src/main/java/com/azure/ai/metricsadvisor/administration/MetricsAdvisorAdministrationAsyncClient.java#L623-L623)
Model Conversion is verified using the unit tests as well.

5. Exception Conversion
Since `azure-core` already has exception type `HttpResponseException` with `ResponseError`, those two types provide more information than MA's customized types. I removed the customized exception conversion in code now. Previously I tried map to customized error for Mono and PagedFlux which proves that if the customer wants to do exception conversion, it's also doable.
But I have not investigate on map error for SyncPoller and PollerFlux. Please let me know if I need to investigate this.

6. Two client issue
We agreed that modifying swagger is the correct way to generate two clients. For now I did not spend time to modify swagger to update operation_id because we know for sure that updating operation_id can generate two clients. I think this is not our first priority. Our purpose is to test grow up stories for different APIs. So I just create `MetricsAdvisorAdministrationClient` and related `Builder` manually and move the APIs we want to test into `MetricsAdvisorAdministrationClient`.
From @srnagar's comment, it's worthwhile to update swagger, so I will update operation_id in swagger and regenerate again.

7. I added a README in my experimental project to explain the codes.
https://github.com/haolingdong-msft/metrics-advisor-poc/blob/b6cb5e5f5cfbd5ce60e810fb5b6ee5185c3eb18a/README.md

8. Add a doc about the process of the experiment: https://github.com/haolingdong-msft/metrics-advisor-poc/blob/master/developer.md

Todo:
Document the grow up story - WIP
Test LRO APIs on other RP
Model convert for SyncPoller and PollerFlux
Test more MA APIs if needed
Add operation_id to swagger to generate two clients - WIP
Customized Exception convert for SyncPoller and PollerFlux?
**Adding model conversion utils for PagedFlux/PagedIterable/SyncPoller/PollerFlux in core?** -> this one needs to be followed up.

**Comment by weidongxu-microsoft** [comment]
done and reviewed by SDK arch board https://github.com/Azure/autorest.java/blob/main/docs/developer/2022-05-18-dpg-archboard-review.md
