### ISSUE TITLE
Architectural question

### ISSUE THREAD

**Issue by jvmlet** [Azure/autorest.java#1364]
Hello. I would really like to understand the design decision NOT to use one of the  available template engines  like all other generators do but go with simple `printLine`. I can see benefits of using AST tools like Roslyn or Java API to generate the code, but please explain your decision to use print-line-generator.

**Comment by weidongxu-microsoft** [comment]
Personal opinion: because AST or not affect very little on final quality of the output code.

AST only make sure the syntax is correct, but it does not even ensure the single file can pass compilation, not to mention the hundreds of files in project, with its dependencies. And after compilation there is checkstyle, spotbugs, revapi, review.

Really the real challenge is to output correct code that works and meets the design guideline https://azure.github.io/azure-sdk/java_introduction.html
E.g. if one does not know what some output code is required to look like this in https://github.com/Azure/autorest.java/pull/1363, AST does not help a bit.

There is multiple (actually 3) sets of AST used in the repo, but mostly on postprocessing to transform the code. There is javac in googleformat, Eclipse language server in postprocess, javaparser in postprocess too.

**Comment by weidongxu-microsoft** [comment]
Yes, AST or not is indeed among the first thought on the code generator (I wasn't the original designer).
AST likely works OK, if this version starts with it (though I would imagine writing lots of e.g. `JavaParser.parseExpression(longLinesOfCode)` instead of really construct an expression/statement from basic pieces).

This autorest.java is actually a plugin for the pipeline https://github.com/Azure/autorest (the last stage of it)

My opinion is that this repo is hard to reuse because it is tight coupled to MS flavored OpenAPI and even more to MS libs (e.g. it only supports azure-core) and code style.
