### ISSUE TITLE
DPG, generate convenience method for simple API

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1537]
First step might be simple method, no pageable, no LRO.

**Comment by weidongxu-microsoft** [comment]
Options:
1. Not generate additional ProxyMethod for API with models, and generate a wrapper convenience method in `AsyncSyncClient` to serialize/de-serialize models and optional parameters to the DPG method. This could be hard, and might have performance issue.
2. Generate additional ProxyMethod as we do in vanilla (so we had 2 sets of ProxyMethod, DPG and vanilla), the higher level would be same as vanilla. This should be easy, but it might have impact on telemetry, as ProxyMethod for DPG and vanilla are essentially same.

---

Given CADL versioning, we should be able to generate all overload that matches the history of the API. This might complicate above discussion.
If V1 and V2 have 2 different set of required/optional parameters, should we further generate 2 sets of ProxyMethod for V2?

---

Do we consider `BarOptions` if there is lots of numbers of parameters?

**Comment by srnagar** [comment]
For option 1, the model can easily be converted to BinaryData. We can just use `BinaryData.fromObject()` and `BinaryData.toObject()` to map the model to BinaryData which can then be used to call the protocol method. So, not sure if it would be harder to write but I'd expect the grow-up methods that devs write also to use this same approach. 

Option 2 is acceptable too. This also seems like relatively less work on the generator and we should rather spend resources on CADL integration and go with option 2 now. Since the proxy methods are internal, we can make changes later if required.

Regarding `BarOptions`, yes, we should create an options bag when we have a large number of params.

**Comment by weidongxu-microsoft** [comment]
First we will have some refactor to `ClientMethod` https://github.com/Azure/autorest.java/pull/1607

Plan on next step, I will prototype an additional mapping of client method to convenience method (still as class `ClientMethod` for now) in `AsyncSyncClient`.
E.g. `BinaryData getFoo(RequestOptions)` to `Foo getFoo(expand, Context)`
Then in template, fill the code for conversion of method call.

At present, I will only target simple method (no pageable, no LRO).

**Comment by weidongxu-microsoft** [comment]
Question: do we provide the overloaded method of "required parameter only"?

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/autorest.java/issues/1670
