### ISSUE TITLE
Fail generation in the emitter if doc is missing/empty

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#1640]
All Tier-1 language DPG generators will fail generation if a doc tag is missing or empty, rather than generating documentation to fill in the gaps. And this would should be implemented in emitter side.

https://github.com/Azure/autorest.csharp/issues/2621

**Comment by weidongxu-microsoft** [comment]
Is it "@doc" or "@summary"?

What's the target? Model? Operation?

Also this likely break lots of tests in cadl-ranch.

**Comment by annelo-msft** [comment]
@weidongxu-microsoft it is all of those.  `@doc` should be provided for client, operations, operation parameters and return types, models, model properties, enums, enum elements, and possibly others - anywhere doc comments are needed in the API surface.

**Comment by weidongxu-microsoft** [comment]
So that should at least include type
- `NamespaceType`, for client
- `OperationType`, for operation
- `EnumType`, for enum; `EnumMemberType`, for enum value
- `ModelTypeProperty`, for both class variable in model and request parameter in operation
- `ModelType` but exclude intrinsic (also might exclude ModelType used as Response, as the Response class is from azure-core), for model/class

---

We might not want to do this too eagerly, as it might break basic emitter function, as cadl-azure-core might lack some required doc e.g. https://github.com/Azure/cadl-azure/blob/9dde245/packages/cadl-azure-core/lib/foundations.cadl#L126

**Comment by annelo-msft** [comment]
Dependent on https://github.com/Azure/cadl-azure/issues/1748
