### ISSUE TITLE
Add nightly CI to test latest TSP releases

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2099]
The TSP team push to npm a package for every single merge to main. The objective of this issue is that the language repo has a nightly build that:
- Install the latest "next" release from npm for all dependencies (compile, azure-core, etc.)
- Run the testsuite as usual

Implementation detail: using [ncu](https://www.npmjs.com/package/npm-check-updates) with `--target @next` should allow for simple package.json update to latest dev version (not tested at the time of this issue).

ETA should be before the next release of the TSP team (early May)

**Comment by weidongxu-microsoft** [comment]
WIP https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2751024&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=cf4477f9-109f-5399-1612-bcbe5909c9f2

**Comment by weidongxu-microsoft** [comment]
Current remaining problem is that tsp seems ignore the options in tspconfig.yaml, as code generates to tsp-output/JavaEmitter, instead of what specified by emitter-output-dir in options.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2755538&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=cf4477f9-109f-5399-1612-bcbe5909c9f2

Not sure whether it is actually a bug on compiler dev release, or problem within this repo.
