### ISSUE TITLE
all client, "setKind" cannot be accessed in model of different package

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#2574]
### mgmt (Jackson)

PR https://github.com/Azure/autorest.java/pull/2563 would introduce a getter method on the discriminator property. This going to be shipped in next release.

Please let us know if mgmt is OK with it. Or we want to delay a bit (as this changes API shape of the model)

Also there maybe some issue with the generated test code.
https://github.com/weidongxu-microsoft/autorest.java_ci/actions/runs/8039220851/job/21956004744#step:11:6672

### dpg (azure-core)

https://github.com/Azure/azure-sdk-for-java/pull/39109#discussion_r1515536323

**Comment by XiaofeiCao** [comment]
The root cause is that parent and child class are not in the same package, and child class calls `withKind` which is a package private method. Reason the `withKind` is package private is that parent class is an output-only model, and polymophic discriminator setter method's visibility is set to package private.
https://github.com/Azure/autorest.java/blob/main/javagen/src/main/java/com/azure/autorest/template/ModelTemplate.java#L193-L227

For consumption case, parent class `ReservationRecommendationInner` (inner class) is in `fluent.models` package, while child class `LegacyReservationRecommendation` is in `models` package.

Make `withKind` protected in mgmt could resolve this.

**Comment by XiaofeiCao** [comment]
Meeting notes:

Use [Accessor pattern](https://github.com/Azure/azure-sdk-for-java/wiki/Access-helpers). Set accessor in parent class and use accessor in child class.

A simpler approach is to make setter protected instead of package-private. Though we probably don't want visibility to be bigger than it should be and we'll break existing code when we switch to using accessor pattern.

**Comment by weidongxu-microsoft** [comment]
Accessor pattern would require generate another helper file?

**Comment by weidongxu-microsoft** [comment]
One thing to consider (if we need `setKind`), whether user can add a subclass. If user can, it would also need to be `protected` (as user need to set the "kind").

**Comment by weidongxu-microsoft** [comment]
For Jackson subclass, I can do 

```java
    @JsonTypeId
    @JsonProperty(value = "odata.type", required = true)
    public Odatatype getOdataType() {
        return Odatatype.MICROSOFT_AZURE_MONITOR_SINGLE_RESOURCE_MULTIPLE_METRIC_CRITERIA;
    }
```

To have `getOdataType` behave as type id.
