### ISSUE TITLE
Multipart Form Data User experience

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2668]

**Comment by weidongxu-microsoft** [comment]
- https://github.com/Azure/azure-sdk-for-java/issues/37488
- https://github.com/Azure/azure-sdk-for-java/issues/38408
- https://github.com/Azure/azure-sdk-for-java/issues/39150

**Comment by weidongxu-microsoft** [comment]
All cases that used by existing service and cadl-ranch test is supported.

We had basic agreement on advanced feature like specifying content-type and additional headers for non-File HttpPart (filename and content-type is good on File HttpPart). The implementation is not started due to lack of real service ask.
