### ISSUE TITLE
Multipart Form Data Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2669]

**Comment by weidongxu-microsoft** [comment]
July: support "required" filename

**Comment by weidongxu-microsoft** [comment]
All cases that used by existing service and cadl-ranch test is supported.

We had basic agreement on advanced feature like specifying content-type and additional headers for non-File HttpPart (filename and content-type is good on File HttpPart). The implementation is not started due to lack of real service ask.
