### ISSUE TITLE
Encode int as string Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2863]

**Comment by weidongxu-microsoft** [comment]
Are service just able to cast every type to every other type?
 
If this comes from Batch (on the "contentLength" in a model that their backend wrongly send a string, but they want to expose a int to customer), they should customize the code for that (they've done that in Jasva, and it is there we notify service on that bug).
From my understanding, this request is not a generic feature. It is just for fixing for a backend bug (that cannot be fixed in backend, maybe due to backward-compatibility issue).
 
I assume for such sporadic incident (only happen on 1 API in 1 service, and that even a bug on backend), customization would be better. We'd talk about feature when we see a 2nd one.

**Comment by weidongxu-microsoft** [comment]
Code merged. Next release 0.19.2 (or 0.20.0) would have the feature.
