### ISSUE TITLE
tsp, investigate timeout in preview CI

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#2923]
https://dev.azure.com/azure-sdk/internal/_build?definitionId=6421

Most of the time it times out.

Our sync job (after release) usually takes about 15min, so I don't think it is due to too many libs.
https://dev.azure.com/azure-sdk/internal/_build?definitionId=6270

Maybe we can see if we first switch it to use tsp-client

**Comment by XiaofeiCao** [comment]
Current observation:
generation stuck at computefleet forever... Starting at around 6min, and all the way till 60min..
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4061705&view=logs&j=336b15cf-fc9c-56ab-208a-614ed6b4889e&t=43edde52-8534-50b4-e90b-6bea0915dd84

**Comment by weidongxu-microsoft** [comment]
Same cause of windows/linux/mac?

**Comment by XiaofeiCao** [comment]
> Same cause of windows/linux/mac machine?

I'm not sure. I need to check in my local env first.

> Though the sync job (after release) is on ubuntu
https://github.com/Azure/autorest.java/blob/main/eng/pipelines/post-publish-sdk.yaml

Yeah, this remains a puzzle to me..

**Comment by weidongxu-microsoft** [comment]
Ah, current preview regen does not use tsp-client.

I guess you may first switch to use tsp-client.

**Comment by XiaofeiCao** [comment]
Finally found the root cause.
Long stories short, fluent branch lacks `System.exit(0)` as dpg branch: https://github.com/Azure/autorest.java/blob/403ffcb32add0d2b9457bb86494ca68ae15605c5/typespec-extension/src/main/java/com/azure/typespec/Main.java#L183

Extended edition:
1. Q: Why we need `System.exit(0)`? Why didn't Java process exit normally?
A: Java process exits when there are only daemon threads running except `main` thread. After adding log to show which non-daemon threads are alive, we could see a suspicious `Thread-0` which is initialized by `Connection`: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4075692&view=logs&j=f0ea25ea-b7e0-596e-c691-94ee910ce8e9&t=4036877c-0fde-50d1-2f32-52f8f5ad201b&l=178
(reason it exits normally is due to `System.exit(0)` already added too)
code: https://github.com/Azure/autorest.java/blob/403ffcb32add0d2b9457bb86494ca68ae15605c5/extension-base/src/main/java/com/azure/autorest/extension/base/jsonrpc/Connection.java#L51
This line starts a non daemon thread which prevents the Java process from exiting normally.
2. Q: Why this stuck only occurs for some pipelines(e.g. nightly and Lite Gen), but others are not(e.g. sync SDK and SDK automation)?
A: If we take a closer look at the `CompletableFuture.runAsync` implementation, it's:
```java
public static CompletableFuture<Void> runAsync(Runnable runnable) {
    return asyncRunStage(ASYNC_POOL, runnable);
}
```
For ASYNC_POOL, it's defined as:
```java
private static final Executor ASYNC_POOL = USE_COMMON_POOL ?
        ForkJoinPool.commonPool() : new ThreadPerTaskExecutor();

private static final boolean USE_COMMON_POOL =
        (ForkJoinPool.getCommonPoolParallelism() > 1);
```
`ForkJoinPool.commonPool()` creates daemon threads, and `ThreadPerTaskExecutor` creates normal(non-daemon) threads.
In addition, `ForkJoinPool.getCommonPoolParallelism()` is determined by `Runtime.getRuntime().availableProcessors()`.
The answer is pretty clear: reason that some pipelines stuck while some didn't is that they are using different agent pool, and different agent pool has different processor cores. 
For those stuck, they have agent pool of processor cores == 1, meaning they will use ThreadPerTaskExecutor, which will create non-daemon threads, preventing Java process from exiting.
For those didn't, they don't have daemon threads.

Solution be, simply add `System.exit(0)` for fluent branch as well.
